[theme]
base = "light"
primaryColor = "#7C5CFF"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0E0E14"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
